### ISSUE TITLE
Day Month, and not Month Day

### ISSUE THREAD

**Issue by tpbillund** [cowboysdude/MMM-Holiday#1]
Hi Nice module
One question, have tried in Holiday to changes how it shows the "AllDate" variable, from Month/Day to Day/Month, but then there are many holidays, that it don't show.

Is there a way to show the date as Day / Month / Year, and still get all the Holidays ?

**Comment by cowboysdude** [comment]
Yes read the README ;)  It tells you how LOL

**Comment by tpbillund** [comment]
LOL ?? Yes now we can read/see it, you have just added the solution - so YES the Readme tells it... NOW.
THX. and LOL to you ;-)
