### ISSUE TITLE
Skip dates, only show remaining days?

### ISSUE THREAD

**Issue by htilly** [cowboysdude/MMM-Holiday#2]
Hi!

First of, thanks for a great module.
Is there any simple way of dropping the actual date and just show the "Name + remaining days" ?

Edit:
Guess what Im asking for is an option to just show:

`holidayDate.innerHTML = holiday.localName + " In " + DateDiff.inDays(d1, d2) + " days";`

/Tilly

**Comment by cowboysdude** [comment]
Yes there is..... check the config sample in the Readme for the change.   You'd need to do a git pull to update.

**Comment by htilly** [comment]
Can´t find the setting in the config.
Just to be clear, I want to be able to drop "allDate".

From:
`holidayDate.innerHTML = allDate + " ~ " + holiday.localName + " In " + DateDiff.inDays(d1, d2) + " days";  `  

To:
`holidayDate.innerHTML = holiday.localName + " In " + DateDiff.inDays(d1, d2) + " days";     `
